# Generated by Django 2.2.7 on 2020-01-08 23:45

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200109_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=5, populate_from=['title']),
        ),
    ]
