# Generated by Django 2.2.7 on 2020-01-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200109_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
