# Generated by Django 2.2.7 on 2020-01-13 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200113_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 13, 21, 18, 883864, tzinfo=utc)),
        ),
    ]
